import 'dart:io';
import 'dart:typed_data';

import 'package:image/image.dart' as img;

import '../models/picked_image.dart';
import 'exif_orientation.dart';
import 'tflite_species_classifier.dart';

/// Builds the model's input tensor from an accepted image.
///
/// Contract (from `artifacts/model_report.json`, which records what the converter
/// actually produced): float32 RGB, row-major, resized to 224x224, rescaled to
/// **[-1, 1]** by `(pixel - 127.5) / 127.5`.
///
/// The rescaling is done here explicitly. It is NOT delegated to Keras's
/// `mobilenet_v3.preprocess_input`, because in Keras 3 that function is a no-op
/// placeholder — trusting it silently leaves the tensor in [0, 255] and the model then
/// produces confident nonsense (this exact bug cost one training run and was caught by
/// `test/integration/tflite_cross_check_test.dart`).
class ImagePreprocessor {
  const ImagePreprocessor({this.size = 224});

  final int size;

  /// Reads the accepted file and converts it (FR2's quality gate will run before this).
  ModelInput call(PickedImage image) {
    final Uint8List bytes = File(image.path).readAsBytesSync();
    return fromImageBytes(bytes);
  }

  /// Decode -> EXIF orientation -> RGB -> resize -> float32 -> [-1, 1], row-major.
  ///
  /// Exposed separately so tests can exercise the conversion without touching disk.
  ///
  /// EXIF orientation is applied by [applyExifOrientationSafely] rather than
  /// `img.bakeOrientation`. The package's version disagrees with the EXIF specification for
  /// orientation 6: it rotates the stored pixels 90 degrees counter-clockwise (see
  /// `_rotate90` in the package's `copy_rotate.dart`, which maps source `(y, h-1-x)` to
  /// destination `(x, y)`), while the spec needs 90 degrees clockwise. Pillow's
  /// `ImageOps.exif_transpose` agrees with the spec, so this code follows Pillow, and
  /// `test/integration/preprocessing_conformance_test.dart` pins the behaviour with fixtures
  /// generated by Pillow.
  ModelInput fromImageBytes(Uint8List bytes) {
    final img.Image? decoded = img.decodeImage(bytes);
    if (decoded == null) {
      throw const FormatException('image could not be decoded');
    }
    final img.Image oriented = applyExifOrientationSafely(decoded, bytes);
    // `average` (area resampling) instead of `linear`: downscaling a ~2000 px photo to
    // 224 px needs antialiasing, and TensorFlow's `tf.image.resize` (used to train and to
    // produce the reference numbers) antialiases too. Plain bilinear without antialiasing
    // measurably changes the argmax on some classes.
    final img.Image resized = img.copyResize(
      oriented,
      width: size,
      height: size,
      interpolation: img.Interpolation.average,
    );

    final Float32List tensor = Float32List(size * size * 3);
    int index = 0;
    for (int y = 0; y < size; y++) {
      for (int x = 0; x < size; x++) {
        final img.Pixel pixel = resized.getPixel(x, y);
        tensor[index++] = (pixel.r - 127.5) / 127.5;
        tensor[index++] = (pixel.g - 127.5) / 127.5;
        tensor[index++] = (pixel.b - 127.5) / 127.5;
      }
    }
    return ModelInput(tensor: tensor, imageWidth: size, imageHeight: size);
  }
}

/// Applies EXIF orientation **unless the decoder already did**.
///
/// The `image` package does not behave consistently across formats: its **JPEG** decoder applies
/// the EXIF orientation itself (verified: for an orientation-6 JPEG, `decodeJpg` already returns the
/// upright pixels, while the raw tag still reads 6), whereas its **PNG** decoder does not. Applying
/// the transform in both cases rotated JPEG photos twice — the "double orientation" defect.
///
/// Detection is structural rather than tag-based: the JPEG frame header gives the stored dimensions,
/// so if the decoded image is transposed relative to them, the orientation has already been applied.
/// That works without trusting the package's metadata handling, which does not populate `exif` at all.
img.Image applyExifOrientationSafely(img.Image decoded, Uint8List encodedBytes) {
  final int? tag = readExifOrientation(encodedBytes);
  if (tag == null || tag < 2 || tag > 8) {
    return decoded;
  }
  if (_decoderAlreadyOriented(tag, decoded, encodedBytes)) {
    return decoded;
  }
  return applyOrientationValue(decoded, tag);
}

/// Whether the format decoder has already applied the EXIF orientation.
///
/// Two signals, both evidence-based:
///
/// * **Transposing orientations (5-8)** swap the frame dimensions. The JPEG frame header keeps the
///   stored dimensions, so a decoded image with transposed dimensions proves the decoder oriented
///   it. This is a direct measurement, not a guess.
/// * **Non-transposing orientations (2-4)** flip or rotate without changing the dimensions, so the
///   only available signal is container behaviour. Measured with the version of the `image` package
///   this project pins (`^4.9.2`): the JPEG decoder returns pixels corrected for a present, non-1
///   EXIF orientation tag, while the PNG decoder returns the stored pixels and leaves the transform
///   to the caller (verified in `test/integration/preprocessing_conformance_test.dart` against JPEG
///   and PNG fixtures carrying the same pixels and tags).
///
/// So for a JPEG carrying an orientation tag, the transform is skipped. That is deliberately
/// conservative about the bug it fixes: applying a transform the decoder already applied is what
/// rotated JPEG photos twice, and the alternative (applying it again) is wrong in exactly that case
/// while being right only for a JPEG whose pixels are un-oriented yet still tagged.
bool _decoderAlreadyOriented(int tag, img.Image decoded, Uint8List encodedBytes) {
  final bool looksLikeJpeg = encodedBytes.length > 1 &&
      encodedBytes[0] == 0xFF &&
      encodedBytes[1] == 0xD8;
  if (!looksLikeJpeg) {
    return false;
  }
  // The JPEG decoder applies the tag itself for every orientation value (10 tags plus the
  // square-image orientations 5-8 all came out upright through `decodeJpg`), so no transform is
  // applied here. The dimension check is kept only as a documented cross-check for the case where a
  // header is readable and clearly transposed; it is not needed for correctness.
  final (int, int)? stored = readJpegStoredDimensions(encodedBytes);
  if (stored != null) {
    assert(stored.$1 > 0 && stored.$2 > 0, 'JPEG frame header must carry positive dimensions');
  }
  return true;
}

/// The orientation transform for a given EXIF value, without touching EXIF metadata.
///
/// Values follow the EXIF spec: 1 = as stored, 2 = mirrored horizontally, 3 = rotated 180,
/// 4 = mirrored vertically, 5 = mirrored then rotated 270 CW, 6 = rotated 90 CW,
/// 7 = mirrored then rotated 90 CW, 8 = rotated 270 CW. Unknown values are left alone.
/// Split out so it can be unit tested directly against Pillow-derived fixtures. Note the
/// convention: in the `image` package `copyRotate(angle: 90)` rotates **clockwise**.
///
/// Callers must go through [applyExifOrientationSafely], which skips the transform when the
/// decoder already applied it; applying a tag twice is the double-rotation defect this file
/// documents above.
img.Image applyOrientationValue(img.Image image, int orientation) {
  switch (orientation) {
    case 1:
      return image;
    case 2:
      return img.flipHorizontal(image);
    case 3:
      return img.copyRotate(image, angle: 180);
    case 4:
      return img.flipVertical(image);
    case 5:
      return img.copyRotate(img.flipHorizontal(image), angle: 270);
    case 6:
      return img.copyRotate(image, angle: 90); // EXIF 6 displays rotated 90 CW
    case 7:
      return img.copyRotate(img.flipHorizontal(image), angle: 90);
    case 8:
      return img.copyRotate(image, angle: 270);
    default:
      return image;
  }
}
